class Autogenerated {
  String userEmail;
  String userPassword;

  Autogenerated({this.userEmail, this.userPassword});

  factory Autogenerated.fromJson(Map<String, dynamic> json) {
    return Autogenerated(
        userEmail: json['user_email'], userPassword: json['user_password']);
  }

  Map toMap() {
    var map = new Map<String, dynamic>();
    map["user_email"] = userEmail;
    map["user_password"] = userPassword;

    return map;
  }
}
